replicaCount: 1

image:
  repository: 311902596413.dkr.ecr.us-east-1.amazonaws.com/linkshrink-analytics
  tag: sha-5886d02
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3003

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "250m"
