replicaCount: 1

image:
  repository: 311902596413.dkr.ecr.us-east-1.amazonaws.com/linkshrink-url
  tag: sha-d78abec
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3002

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "250m"
