replicaCount: 1

image:
  repository: 311902596413.dkr.ecr.us-east-1.amazonaws.com/linkshrink
  tag: sha-0000000
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "200m"
